### PR TITLE
Fixes #7

### LINKED ISSUE #7: Set up continuous deployment
Ideally we would have a github action that can be triggered and will create a new release on github with an installer. We (Ace Centre) can then sign those installers, although that has to be done manually as we have to use a physical key in the process.

We also want it to be easier for users to update. It doesn't have to be automatic but they should be able to update to the latest version easily.

This maybe already works but it just needs checked

### PR DESCRIPTION
**Pull request by gavinhenderson**

### CODE REVIEW

**Comment by gavinhenderson** [comment]
Hey @sjjhsjjh 

I've made some minor tweaks:
* I split the 'check' job into two smaller steps. One is 'GetVersion' and the other is 'RuffCheck'. Just makes it slightly clearer if a step ever fails we know what it was specifically doing. The release version is dependent on them both.
* I set the release to be 'draft'. My thinking is that we will release a draft then when we manually sign it we can publish it fully. 

Besides that im happy to merge as long as you are happy with my changes?

**Comment by sjjhsjjh** [comment]
Hi Gavin, I think I preferred Prerelease to Draft. The reason is that Draft releases aren't even visible to the public. That means they can't be discovered through the unauthenticated API, which the app uses now.
Ace Centre could remove the Prerelease flag when the signed assets are uploaded.

**Comment by gavinhenderson** [comment]
@sjjhsjjh ah yeah you are totally right, I hadn't realised pre-release was on. I've undone my commit! You happy if I merge this now and we can just do a seperate PR commit for the docs? (or if its just MD files feel free to work on master)

**Comment by sjjhsjjh** [comment]
Sounds good.
I'll aim to have the developer docco done by the end of the week and will raise another PR on the same branch at that time.

**Comment by sjjhsjjh** [comment]
Hi @gavinhenderson , One of the checks failed. I think it's because the merge to main counts as a commit of the Version.ini file, which in turn kicks of a release build. That fails because the tag, which is based on the version number, already exists.
You can merge anyway, or remove the tag, or see about modifying the YAML so it only picks up non-merge commits I think.

**Pull request merged**
